# Generated by Django 5.1.1 on 2024-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
