# Generated by Django 5.1.1 on 2024-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_alter_comment_createdat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="commenter_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
